apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  selector:
    matchLabels:
      app: second-app
  replicas: 1
  template:
    metadata:
      labels:
        app: second-app
    spec:
      containers:
      - name: second-node
        image: mrkewl/kub-first-app
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: <Port>
